{% set name = "ctre" %}
{% set version = "3.10.0" %}
{% set sha256 = "b17e6c9a6cc0cea65132f62a6c699cefed952721063569d6339eb3ca471045e6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hanickadot/compile-time-regular-expressions/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  run:
    - __unix  # [unix]
    - __win  # [win]

test:
  commands:
    - test -d ${PREFIX}/include/ctll  # [unix]
    - test -d ${PREFIX}/include/ctre  # [unix]
    - test -d ${PREFIX}/include/unicode-db  # [unix]
    - test -f ${PREFIX}/include/ctll.hpp  # [unix]
    - test -f ${PREFIX}/include/ctre.hpp  # [unix]
    - test -f ${PREFIX}/include/ctre-unicode.hpp  # [unix]
    - test -f ${PREFIX}/include/unicode-db.hpp  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ctll\fixed_string.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\ctre\pcre.hpp (exit 1)  # [win]


about:
  home: https://github.com/hanikadot/compile-time-regular-expressions
  summary: 'Compile Time Regular Expression in C++'
  description: |
    Fast compile-time regular expressions with support for
    matching/searching/capturing during compile-time or runtime.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - faceprint
